version: "2"

run:
  timeout: 5m


linters:
  disable:
    - containedctx
    - cyclop
    - depguard
    - exhaustruct
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - err113
    - mnd
    - ireturn
    - nlreturn
    - nonamedreturns
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl

  settings:
    goconst:
      min-len: 2
      min-occurrences: 2
    misspell:
      locale: US
    lll:
      line-length: 140
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental
    revive:
      severity: warning
      enable-all-rules: false
    sloglint:
      no-mixed-args: true
      kv-only: true
      context: all
      static-msg: true
      # Enforce a single key naming convention. Values: snake, kebab, camel, pascal. Default: ""
      key-naming-case: snake    

  exclusions:
    paths:
      - vendor
      - pkg/gen

    rules:
      - text: "at least one file in a package should have a package comment"
        linters:
          - stylecheck
      - text: "should have a package comment"
        linters:
          - golint
          - revive
      - path: app/cmd/smtpd-proxy\.go
        linters:
          - lll
      - path: _test\.go
        linters:
          - containedctx
          - dupl
          - errcheck
          - forcetypeassert
          - funlen
          - gosec
          - noctx
          - paralleltest
          - testifylint
          - testpackage
          - thelper
          - wrapcheck
      - path: e2e/.*\.go
        linters:
          - gosec
          - dupl
          - wrapcheck
      - path: cmd/.*\.go
        linters:
          - gochecknoinits
