name: ci-flow

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  lint:
    name: run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          skip-pkg-cache: true
  test:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.0
      - name: Build & test
        run: make ci-test
      - name: Upload log files
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report.log
          path: |
            **/*.log
          if-no-files-found: error
