name: Main pipeline

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request: {}

jobs:
  ci-lint:
    name: run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with: { go-version: 1.20.3 }
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
  ci-test:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with: { go-version: 1.20.3 }
      - name: Build & test
        run: make ci-test
      - name: Upload log files
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-report.log
          path: |
            **/*.log
          if-no-files-found: error
