name: release-tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-docker-image:
    name: Build and upload artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Setup Golang caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-          

      - name: Pull source
        uses: actions/checkout@v1
      
      - name: Build release
        run: make release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            smtpd-proxy.yml
            bin/smtpd-proxy-darwin-arm64
            bin/smtpd-proxy-windows-arm64.exe
            bin/smtpd-proxy-linux-arm64
            # bin/report-tests.xml
            # bin/report-lint.xml

      - name: Done
        run: echo Done
      